const API_URL = 'https://prajwalp12.app.n8n.cloud/webhook/astrolive-dashboard';
let dashboardData = null, controller = null;
const $ = (selector) => document.querySelector(selector);
const safeArray = (value) => Array.isArray(value) ? value : [];
const safeNumber = (value) => { const n = Number(value); return Number.isFinite(n) ? n : null; };
const escapeHTML = (value) => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const formatNumber = (value) => safeNumber(value) === null ? 'Not available' : new Intl.NumberFormat().format(safeNumber(value));
const formatScore = (value) => safeNumber(value) === null ? 'Not available' : safeNumber(value).toLocaleString(undefined,{maximumFractionDigits:1});
const formatPercent = (value) => safeNumber(value) === null ? 'Not available' : `${safeNumber(value).toLocaleString(undefined,{maximumFractionDigits:1})}%`;
const formatRating = (value) => safeNumber(value) === null || safeNumber(value) <= 0 ? 'N/A' : `${safeNumber(value).toLocaleString(undefined,{maximumFractionDigits:1})} / 5`;
const formatDate = (value) => { const date = new Date(value); return value && !Number.isNaN(date) ? date.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}) : 'Not available'; };
const getSourceEntries = (data) => Object.entries(data?.sources && typeof data.sources === 'object' ? data.sources : {});
const normalize = (data) => data && typeof data === 'object' ? data : {};
function sentimentClass(value){const x=String(value||'').toLowerCase();return ['positive','negative','mixed'].includes(x)?x:'neutral'}
function listItems(items, key){return safeArray(items).map(item => `<li>${escapeHTML(typeof item === 'object' ? item[key] ?? item.name ?? item.theme ?? item.pain_point ?? '' : item)}</li>`).join('')}
function rankList(items, nameKey, pain=false){const array=safeArray(items).filter(x=>x && String(x[nameKey] ?? '').toLowerCase() !== 'unknown');if(!array.length)return '<div class="empty">No analyzed themes available.</div>';const max=Math.max(...array.map(x=>safeNumber(x.count)||0),1);return `<div class="rank-list ${pain?'pain':''}">${array.map((item,i)=>{const count=safeNumber(item.count)||0;return `<div class="rank-row"><span class="rank-num">${String(i+1).padStart(2,'0')}</span><div><div class="rank-text">${escapeHTML(item[nameKey])}</div><div class="bar"><i style="width:${Math.min(100,count/max*100)}%"></i></div></div><span class="count">${formatNumber(count)}</span></div>`}).join('')}</div>`}
function emptyOr(value, title){return value ? escapeHTML(value) : `<span class="focus-note">${title || 'Not available'}</span>`}
function render(data){dashboardData=normalize(data);const d=dashboardData.dashboard||{}, s=dashboardData.sentiment||{}, trust=dashboardData.trust||{}, sources=getSourceEntries(dashboardData), reviews=safeArray(dashboardData.recent_reviews);const positive=safeNumber(s.positive)||0, neutral=safeNumber(s.neutral)||0, negative=safeNumber(s.negative)||0, mixed=safeNumber(s.mixed)||0, sum=positive+neutral+negative+mixed;const donut=sum?`conic-gradient(var(--success) 0 ${positive}%,var(--neutral) ${positive}% ${positive+neutral}%,var(--danger) ${positive+neutral}% ${positive+neutral+negative}%,var(--warning) ${positive+neutral+negative}% 100%)`:'#edf0eb';const maxTopic=Math.max(...safeArray(dashboardData.topics).map(x=>safeNumber(x.count)||0),1);
  const sourceRows=sources.map(([name,x])=>`<tr><td class="source-name">${escapeHTML(name)}${isHighest(sources,name,'average_trust_score')?'<span class="flag">highest trust</span>':''}</td><td>${formatNumber(x.total_reviews)}</td><td>${formatRating(x.average_rating)}</td><td>${formatScore(x.average_sentiment_score)}</td><td>${formatScore(x.average_trust_score)}</td><td>${formatPercent(x.positive_pct)}</td><td>${formatPercent(x.negative_pct)}</td><td>${formatPercent(x.trust_concern_pct)}</td></tr>`).join('');
  $('#pageContent').innerHTML=`
  <section id="overview" class="section"><div class="section-header"><div><h2 class="section-title">At a glance</h2><p class="section-copy">Full dataset overview · filters below affect detailed feedback only</p></div></div><div class="kpis"><article class="card kpi"><div class="kpi-label">Total reviews</div><div class="kpi-value">${formatNumber(d.total_reviews)}</div><div class="kpi-help">Reviews analyzed by the intelligence pipeline</div></article><article class="card kpi"><div class="kpi-label">Average rating</div><div class="kpi-value">${formatRating(d.average_rating)}</div><div class="kpi-help">Rating data where platforms provide it</div></article><article class="card kpi"><div class="kpi-label">Overall sentiment</div><div class="kpi-value">${emptyOr(d.overall_sentiment)}</div><div class="kpi-help">API-provided classification</div></article><article class="card kpi"><div class="kpi-label">Avg. sentiment score</div><div class="kpi-value">${formatScore(d.average_sentiment_score)}</div><div class="kpi-help">Score on the API’s native scale</div></article><article class="card kpi"><div class="kpi-label">Trust score</div><div class="kpi-value">${formatScore(d.average_trust_score)}</div><div class="kpi-help">Review-extracted trust signal</div></article></div></section>
  <section class="section split-grid"><article class="card" id="sentiment"><div class="section-header"><div><h2 class="section-title">Sentiment Overview</h2><p class="section-copy">Composition of analyzed review sentiment</p></div></div>${sum?`<div class="sentiment-layout"><div class="donut" style="background:${donut}" role="img" aria-label="Positive ${formatPercent(positive)}, neutral ${formatPercent(neutral)}, negative ${formatPercent(negative)}, mixed ${formatPercent(mixed)}"><span>Sentiment<br>mix</span></div><div class="sentiment-list">${[['positive',positive],['neutral',neutral],['negative',negative],['mixed',mixed]].map(([n,v])=>`<div class="legend-row"><i class="swatch ${n}"></i>${n}<b>${formatPercent(v)}</b></div>`).join('')}</div></div>`:'<div class="empty">No sentiment composition is available yet.</div>'}</article><article class="card" id="trust"><div class="section-header"><div><h2 class="section-title">Trust Signal</h2><p class="section-copy">Extracted from review language</p></div></div><div class="trust-score">${formatScore(trust.average_score)}</div><div class="mini-stat"><span>Trust concern</span><b>${formatPercent(trust.trust_concern_pct)}</b></div><p class="trust-note">This is a customer trust signal extracted from reviews, not a statistically validated market-wide trust score.</p></article></section>
  <section class="section" id="sources"><div class="section-header"><div><h2 class="section-title">Source Intelligence</h2><p class="section-copy">Platform-level feedback compared using reported API metrics</p></div></div><article class="card">${sources.length?`<div class="table-wrap"><table class="comparison"><thead><tr><th>Source</th><th>Reviews</th><th>Avg. rating</th><th>Sentiment</th><th>Trust</th><th>Positive</th><th>Negative</th><th>Trust concern</th></tr></thead><tbody>${sourceRows}</tbody></table></div>`:'<div class="empty">No platform data is currently available.</div>'}</article></section>
  <section class="section two-col"><article class="card"><div class="section-header"><div><h2 class="section-title">Pain Points</h2><p class="section-copy">Recurring friction identified by AI analysis</p></div></div>${rankList(dashboardData.pain_points,'pain_point',true)}</article><article class="card"><div class="section-header"><div><h2 class="section-title">Positive Themes</h2><p class="section-copy">What customers repeatedly value</p></div></div>${rankList(dashboardData.positive_themes,'theme')}</article></section>
  <section class="section" id="topics"><div class="section-header"><div><h2 class="section-title">Top Topics</h2><p class="section-copy">Frequently discussed aspects of the AstroLive experience</p></div></div><div class="topic-grid">${safeArray(dashboardData.topics).length?safeArray(dashboardData.topics).map(x=>`<article class="topic"><strong>${escapeHTML(x.name)}</strong><span>${formatNumber(x.count)} mentions</span><div class="bar"><i style="width:${Math.min(100,(safeNumber(x.count)||0)/maxTopic*100)}%"></i></div></article>`).join(''):'<div class="empty">No topics detected.</div>'}</div></section>
  <section class="section" id="reviews"><div class="section-header"><div><h2 class="section-title">What Customers Are Saying</h2><p class="section-copy" id="reviewCount">Loading filtered feedback</p></div></div><div id="reviewResults" class="review-grid"></div></section>
  ${renderExecutive(dashboardData.executive_summary)}
  <section class="section"><article class="card"><div class="section-header"><div><h2 class="section-title">Data Sources</h2><p class="section-copy">Architecture status reflects sources returned by the current intelligence API.</p></div></div><div class="source-types">${['Google Play','Apple App Store','Reddit',...sources.map(x=>x[0])].filter((x,i,a)=>a.indexOf(x)===i).map(n=>`<span class="${sources.some(x=>x[0].toLowerCase()===n.toLowerCase())?'analyzed':''}">${escapeHTML(n)} · ${sources.some(x=>x[0].toLowerCase()===n.toLowerCase())?'Analyzed':'Integration pending'}</span>`).join('')}</div></article></section>`;
  fillFilterOptions(reviews); renderReviews(); $('#footerUpdate').textContent=`Last successful API update: ${formatDate(dashboardData.generated_at)}`;
}
function isHighest(sources, name, key){const values=sources.map(x=>safeNumber(x[1][key])).filter(v=>v!==null);const current=safeNumber(sources.find(x=>x[0]===name)?.[1][key]);return values.length>1&&current!==null&&current===Math.max(...values)&&values.filter(v=>v===current).length===1}
function renderExecutive(e){e=normalize(e);const blocks=[['What is going wrong?','top_customer_pain_points'],['What is working?','top_positive_themes'],['Product issues','top_product_issues']].filter(x=>safeArray(e[x[1]]).length).map(([title,key])=>`<div class="exec-block"><h3>${title}</h3><ul>${listItems(e[key])}</ul></div>`).join('');const narratives=[['Emerging issues','emerging_issues'],['Source comparison','source_comparison']].filter(x=>e[x[1]]).map(([title,key])=>`<div class="exec-block"><h3>${title}</h3><p>${escapeHTML(e[key])}</p></div>`).join('');const recs=safeArray(e.prioritized_recommendations);if(!blocks&&!narratives&&!recs.length&&!e.major_ai_concerns&&!e.major_astrologer_concerns)return '';return `<section class="section" id="executive"><article class="card executive"><div class="section-header"><div><h2 class="section-title">AI Executive Intelligence</h2><p class="exec-intro">The strategic layer: evidence synthesized from the analyzed customer feedback.</p></div></div>${blocks?`<div class="executive-grid">${blocks}${narratives}</div>`:''}${(e.major_ai_concerns||e.major_astrologer_concerns)?`<div class="section-header" style="margin-top:18px"><div><h2 class="section-title">AI vs Human Astrologer Trust</h2><p class="section-copy">Qualitative evidence from analyzed reviews — not a statistical comparison.</p></div></div><div class="qualitative"><div class="exec-block"><h3>AI concerns</h3><p>${emptyOr(e.major_ai_concerns,'No AI-specific concern reported.')}</p></div><div class="exec-block"><h3>Astrologer concerns</h3><p>${emptyOr(e.major_astrologer_concerns,'No astrologer-specific concern reported.')}</p></div></div>`:''}${recs.length?`<div class="section-header" style="margin-top:18px"><div><h2 class="section-title">Prioritized Recommendations</h2><p class="section-copy">Actions supplied by the executive analysis</p></div></div><div class="recommendations">${recs.map((r,i)=>`<div class="recommendation"><span class="priority">${i+1}</span><span>${escapeHTML(typeof r==='object'?r.recommendation??r.text??JSON.stringify(r):r)}</span></div>`).join('')}</div>`:''}</article></section>`}
function fillFilterOptions(reviews){const source=$('#sourceFilter'),sentiment=$('#sentimentFilter'),oldS=source.value,oldT=sentiment.value;source.innerHTML='<option value="all">All platforms</option>'+[...new Set(reviews.map(x=>x.source).filter(Boolean))].map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(x)}</option>`).join('');sentiment.innerHTML='<option value="all">All sentiment</option>'+[...new Set(reviews.map(x=>x.sentiment).filter(Boolean))].map(x=>`<option value="${escapeHTML(x)}">${escapeHTML(x)}</option>`).join('');source.value=oldS;sentiment.value=oldT}
function renderReviews(){if(!dashboardData)return;const source=$('#sourceFilter').value,sentiment=$('#sentimentFilter').value,query=$('#searchFilter').value.trim().toLowerCase();const reviews=safeArray(dashboardData.recent_reviews).filter(r=>(source==='all'||r.source===source)&&(sentiment==='all'||r.sentiment===sentiment)&&(!query||String(r.review_text||'').toLowerCase().includes(query)));$('#reviewCount').textContent=`${reviews.length} matching review${reviews.length===1?'':'s'} · filters apply to this detailed feedback`;$('#reviewResults').innerHTML=reviews.length?reviews.map(r=>`<article class="card review-card"><div class="review-head"><span class="badge">${escapeHTML(r.source||'Source')}</span><span class="badge ${sentimentClass(r.sentiment)}">${escapeHTML(r.sentiment||'Unclassified')}</span></div><p class="review-text">${escapeHTML(r.review_text||'No review text available.')}</p><div class="review-meta"><span>Rating: ${formatRating(r.rating)}</span><span>Trust: ${formatScore(r.trust_score)}</span></div></article>`).join(''):'<div class="empty">No reviews match these filters. Try broadening your search.</div>'}
async function loadDashboard(){if(controller)controller.abort();controller=new AbortController();const btn=$('#refreshButton');btn.disabled=true;btn.textContent='Refreshing…';$('#connectionStatus').className='connection loading';$('#connectionStatus').innerHTML='<i></i>Connecting';try{const res=await fetch(API_URL,{signal:controller.signal,headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`Request failed (${res.status})`);const payload=await res.json();if(!payload||payload.ok===false)throw new Error('The intelligence API did not return a valid response.');render(payload);$('#connectionStatus').className='connection';$('#connectionStatus').innerHTML='<i></i>Live intelligence connected'}catch(err){if(err.name==='AbortError')return;dashboardData=null;$('#pageContent').innerHTML=`<section class="error-view"><h2>Unable to load review intelligence</h2><p>Check the dashboard connection and try again.</p><button class="refresh" id="retryButton">Retry connection</button></section>`;$('#retryButton').addEventListener('click',loadDashboard);$('#connectionStatus').className='connection error';$('#connectionStatus').innerHTML='<i></i>Connection unavailable';$('#footerUpdate').textContent='No successful API update available'}finally{btn.disabled=false;btn.textContent='Refresh dashboard'}}
$('#refreshButton').addEventListener('click',loadDashboard);['sourceFilter','sentimentFilter','searchFilter'].forEach(id=>$("#"+id).addEventListener(id==='searchFilter'?'input':'change',renderReviews));$('#resetFilters').addEventListener('click',()=>{$('#sourceFilter').value='all';$('#sentimentFilter').value='all';$('#searchFilter').value='';renderReviews()});$('#menuButton').addEventListener('click',()=>{const side=$('#sidebar'),open=side.classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',open)});loadDashboard();
